name: graph_rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - pip:
    - gliner
    - huggingface_hub
    - langchain
    - langchain-chroma 
    - langchain-community
    - langchain-openai
    - langchain-text-splitters
    - markitdown[pdf]
    - networkx
    - pandas
    - sentence_transformers